root:
  askformore: false
  autoclip: true
  autoprint: false
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: true
  path: gpgcli-gitcli-fs+file:///home/bemeurer/.password-store
  recipient_hash: {}
  safecontent: false
  usesymbols: false
mounts: {}
